### ISSUE TITLE
Bug: not mobile responsive, content overlapping

### ISSUE THREAD

**Issue by hannesxc** [vanya31/vanya31.github.io#1]
Site has tons of overlapping content, and isn't mobile responsive atm. I can try to make it better and add placeholder sections for you to replace with your about me stuff (if I have time in the upcoming weeks). If you think this is a valid issue, feel free to assign this to me.

**Comment by vanya31** [comment]
Yes ik, it was a beginner project and I kinda stopped working on it because of other engagements. If you wanna work on it and can suggest improvements sure why not. I'm still learning the responsiveness part.
